version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - run:
          name: Build project
          command: ./gradlew clean assemble
      - run:
          name: Run unit tests
          command: ./gradlew test
      
      - run:
          name: Deploy to GitHub Packages
          command: |
            mvn deploy \
              -Dmaven.test.skip=true \
              -DskipTests \
              -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Goodiec/adl \
              -DrepositoryId=github \
              -Durl=https://maven.pkg.github.com/Goodiec/adl \
              -Dfile=target/androidlibrary-1.0-SNAPSHOT.jar \
              -DpomFile=pom.xml \
              -Dsources=target/androidlibrary-1.0-SNAPSHOT.jar \
              -Djavadoc=target/androidlibrary-1.0-SNAPSHOT.jar \
              -Dgpg.skip=true
    environment:
      MAVEN_OPTS: "-Xmx2048m"

workflows:
  build:
    jobs:
      - build