version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: maven:3-jdk-11
    steps:
      - checkout
      - run:
          name: Install Android SDK
          command: |
            wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            unzip -q sdk-tools-linux-4333796.zip -d android-sdk-linux
            echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-29" "build-tools;29.0.3"
      - run:
          name: Build project
          command: ./gradlew clean assemble
      - run:
          name: Run unit tests
          command: ./gradlew test
      - run:
          name: Deploy to GitHub Packages
          command: |
            mvn deploy -Dregistry=https://maven.pkg.github.com/Goodiec/adl \
              -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Goodiec/_androidlibrary \
              -Dusername=${GITHUB_USERNAME} -Dpassword=${GITHUB_TOKEN}