version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:19.0.2-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo add-apt-repository ppa:openjdk-r/ppa \
            sudo apt-get update && sudo apt-get install -y \
              openjdk-11-jdk \
              wget \
              unzip \
              maven 
            wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            unzip -q sdk-tools-linux-4333796.zip -d android-sdk-linux
            echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-29" "build-tools;29.0.3"
      - run:
          name: Set up environment variables
          command: |
            echo 'export ANDROID_HOME=/home/circleci/project/android-sdk-linux' >> $BASH_ENV
            echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:/usr/share/maven/bin' >> $BASH_ENV
      - run:
          name: Install Android Studio
          command: |
            wget https://dl.google.com/dl/android/studio/ide-zips/4.1.3.0/android-studio-ide-201.7199119-linux.tar.gz
            tar -xzf android-studio-ide-201.7199119-linux.tar.gz
      - run:
          name: Build project
          command: ./gradlew clean assemble
      - run:
          name: Run unit tests
          command: ./gradlew test
      
      - run:
          name: Deploy to GitHub Packages
          command: |
            mvn clean deploy -Dregistry=https://maven.pkg.github.com/Goodiec/adl \
              -DaltDeploymentRepository=github::https://maven.pkg.github.com/Goodiec/_adl \
              -Dusername=${GITHUB_USERNAME} -Dpassword=${GITHUB_TOKEN}

workflows:
  build:
    jobs:
      - build